name: WakaTime stat update in README.md

on:
  schedule:
    # Runs at 5 am  '0 0 * * *'  UTC
    - cron: '0 5 * * *'
jobs:
  update-readme:
    name: Update the WakaTime Stat
    runs-on: ubuntu-latest
    steps:
      - uses: Anita-joseph/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TITLE: true

