name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 2am UTC every day of the week
    - cron: '0 2 * * 1-5'

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: avinal/Profile-Readme-WakaTime@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          USERNAME: Anita-joseph
          SHOW_TITLE: false;
